/* DO NOT EDIT THIS FILE - it is machine generated */
#pragma clang diagnostic push
#pragma ide diagnostic ignored "CannotResolve"
#include <jni.h>
/* Header for class com_lzq_androidcontroldemo_utils_NdkUtil */

#ifndef _Included_com_lzq_androidcontroldemo_utils_NdkUtil
#define _Included_com_lzq_androidcontroldemo_utils_NdkUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lzq_androidcontroldemo_utils_NdkUtil
 * Method:    getMD5
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lzq_androidcontroldemo_utils_NdkUtil_getMD5
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

#pragma clang diagnostic pop